name: barmaster
description: Application de gestion pour débits de boisson
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  path_provider: ^2.1.0
  intl: ^0.18.0
  
  # Bluetooth
  flutter_bluetooth_serial_plus: ^0.5.6
  esc_pos_printer: ^4.0.0
  esc_pos_utils: ^1.1.0
  
  # Supabase
  supabase_flutter: ^2.8.0
  
  # Stockage
  shared_preferences: ^2.2.0
  
  # Connectivité (hors connexion)
  connectivity_plus: ^5.0.0
  url_launcher: ^6.3.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
